# Generated by Django 5.2.3 on 2025-06-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='followers',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='following',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='posts',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
