# Generated by Django 5.2.3 on 2025-06-17 14:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_posts_registeruser_posts_no_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='profile',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
