# Generated by Django 5.2.3 on 2025-06-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_registeruser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='posts_no',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
