# Generated by Django 5.2.3 on 2025-06-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_registeruser_posts_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='posts_no',
            field=models.IntegerField(default=0),
        ),
    ]
