# Generated by Django 5.2.3 on 2025-06-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_registeruser_posts_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='posts_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
