# Generated by Django 5.2.3 on 2025-06-21 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_message_receiver_message_read_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
