# Generated by Django 5.2.3 on 2025-06-21 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
    ]
