# Generated by Django 5.2.3 on 2025-06-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
