# Generated by Django 5.2.3 on 2025-06-23 08:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_story_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='video',
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
